# Generated by Django 5.2.4 on 2025-08-04 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('processed_text', models.TextField()),
                ('language', models.CharField(default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_text', models.CharField(max_length=200)),
                ('entity_type', models.CharField(choices=[('topic', 'Topic'), ('concept', 'Concept'), ('person', 'Person'), ('date', 'Date'), ('other', 'Other')], max_length=50)),
                ('start_position', models.IntegerField()),
                ('end_position', models.IntegerField()),
                ('processed_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='nlp.processedquestion')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent_type', models.CharField(choices=[('definition', 'Definition'), ('explanation', 'Explanation'), ('comparison', 'Comparison'), ('example', 'Example'), ('unknown', 'Unknown')], max_length=50)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('processed_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intents', to='nlp.processedquestion')),
            ],
        ),
    ]
